import os
import time
import re
from utils import *
from student_utils import *
from php_from_tsp import php_solver_from_tsp 
from ptp_solver import ptp_solver


class PTP_CLI:
    """
    Interactive command-line client for managing and testing solvers.
    """

    PROMPT_MESSAGE = """
---------------------------------------------
Enter a command
Type 'exit' or presee Escape or Enter to quit
Type '--help' to get more information
----------------------------------------------
"""

    HELP_MESSAGE = """
Commands:
  ls_input: list all input files (default under ./inputs folder)
  ck_input: check whether student created inputs are valid or not
  test_php: test php solver 
  test_ptp: test ptp solver
  test_php_all: test php solver on all input files
  test_ptp_all: test ptp solver on all input files

To quit the client: type 'exit' or press Escape or Enter

Type --help to get help instructions
"""

    def __init__(self, input_dir="./inputs", stu_in_files=None):
        self.INPUT_FILE_DIRECTORY = input_dir
        self.in_files = []
        self.stu_in_files = stu_in_files or ['20_03.in', '20_10.in', '40_03.in', '40_10.in']

    # --- Core loop ---
    def run(self):
        """Run the CLI loop"""
        print(f"{TITLE_ART}")
        while True:
            user_input = input(self.PROMPT_MESSAGE)
            cmd = '_'.join(re.split(r'[_,.\s-]', user_input.lower()))

            if user_input.lower() == "exit" or user_input == "" or user_input == chr(27):
                print("Exit the client")
                break
            elif user_input.lower() == "--help":
                print(self.HELP_MESSAGE)
            elif cmd == "ls_input":
                self.ls_input()
            elif cmd == "ck_input":
                self.ck_input()
            elif cmd == "test_php":
                self.test_php()
            elif cmd == "test_ptp":
                self.test_ptp()
            elif cmd == "test_php_all":
                self.test_php_all()
            elif cmd == "test_ptp_all":
                self.test_ptp_all()
            else:
                print("Command not found.\nType '--help' to get instruction list")

    # --- Helper methods ---
    def ensure_in_files_loaded(self):
        if not self.in_files:
            self.in_files = get_files_with_extension(
                os.path.join(os.getcwd(), self.INPUT_FILE_DIRECTORY),
                extension=".in"
            )

    # --- Command implementations ---
    def ls_input(self):
        print(f"Listing input files under {self.INPUT_FILE_DIRECTORY}")
        self.ensure_in_files_loaded()
        for file in self.in_files:
            print(file)

    def ck_input(self):
        print("Checking whether student created inputs are legitimate...")
        print(f"Searching for specified inputs {self.stu_in_files}")
        self.ensure_in_files_loaded()

        file_paths, in_message = input_file_names_to_file_path(
            ' '.join(sorted(self.in_files)), self.in_files
        )

        count = valid_count = 0
        for file in file_paths:
            file_basename = os.path.basename(file)
            if file_basename in self.stu_in_files:
                print(f"\nChecking file {file_basename}...")
                is_valid, message = is_valid_input(file)
                if is_valid:
                    print("The input is valid")
                    valid_count += 1
                else:
                    print(f"The input is not valid. Error message:\n{message}")
                count += 1

        print(f"\nSuccessfully checked {count} files \n {valid_count} valid")
        if in_message:
            print(in_message)

    def test_php(self):
        print("Testing php solver...")
        user_in_files_str = input("Select input files: ")
        self.ensure_in_files_loaded()

        file_paths, message = input_file_names_to_file_path(user_in_files_str, self.in_files)
        count = legitimate_count = 0
        for file in file_paths:
            print(f"\nReading file {os.path.basename(file)}...")
            G, H, alpha = input_file_to_instance(file)
            print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
            print('Graph constructed...')
            tour = php_solver_from_tsp(G, H)
            print('Tour generated by php solver...')
            print('Analyzing the solution...')
            is_legitimate, driving_cost, walking_cost = analyze_solution(G, H, alpha, tour, {})
            if is_legitimate:
                legitimate_count += 1
            print(f"Your solution is{' NOT' if not is_legitimate else ''} legitimate.")
            print(f"Total driving cost of your solution: {driving_cost:.5f}")
            count += 1

        print(f"\nSuccessfully tested {count} files \n {legitimate_count} solutions legitimate")
        if message:
            print(message)

    def test_ptp(self):
        print("Testing PTP solver...")
        user_in_files_str = input("Select input files: ")
        print("Starting testing PTP solver...")
        self.ensure_in_files_loaded()

        file_paths, message = input_file_names_to_file_path(user_in_files_str, self.in_files)
        count = legitimate_count = 0
        for file in file_paths:
            print(f"\nReading file {os.path.basename(file)}...")
            G, H, alpha = input_file_to_instance(file)
            print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
            print('Graph constructed...')
            tour, pick_up_locs_dict = ptp_solver(G, H, alpha)
            print('Tour generated by PTP solver...')
            print("Writing solution to output file...")
            write_ptp_solution_to_out(tour, pick_up_locs_dict, os.path.basename(file))
            print("Output written.")
            print('Analyzing the solution...')
            is_legitimate, driving_cost, walking_cost = analyze_solution(G, H, alpha, tour, pick_up_locs_dict)
            if is_legitimate:
                legitimate_count += 1
            print(f"Your solution is{' NOT' if not is_legitimate else ''} legitimate.")
            print(f"Total driving cost: {driving_cost:.5f}")
            print(f"Total walking cost: {walking_cost:.5f}")
            count += 1

        print(f"\nSuccessfully tested {count} files \n {legitimate_count} solutions legitimate")
        if message:
            print(message)

    def test_php_all(self):
        print("Testing php solver on all inputs...")
        self.ensure_in_files_loaded()

        file_paths, message = input_file_names_to_file_path(' '.join(sorted(self.in_files)), self.in_files)
        count = legitimate_count = 0
        scores = []

        for file in file_paths:
            print(f"\nReading file {os.path.basename(file)}...")
            G, H, alpha = input_file_to_instance(file)
            print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
            print('Graph constructed...')
            start_time = time.time()
            php_tour = php_solver_from_tsp(G, H)
            php_time = time.time() - start_time
            print('Tour generated by php solver...')
            print('Analyzing the solution...')
            php_is_legitimate, php_driving_cost, php_walking_cost = analyze_solution(G, H, alpha, php_tour, {})
            php_cost = php_driving_cost + php_walking_cost
            if php_is_legitimate:
                legitimate_count += 1
            print(f"Your php solution is{' NOT' if not php_is_legitimate else ''} legitimate.")
            print(f"Total cost: {php_cost:.5f}")
            print(f"Running time: {php_time:.5f} seconds")
            scores.append(php_cost)
            count += 1

        print(f"\nSuccessfully tested {count} files \n {legitimate_count} legitimate")
        print(f"Average cost: {sum(scores)/len(scores):.5f}")
        if message:
            print(message)

    def test_ptp_all(self):
        print("Testing PTP solver on all inputs...")
        self.ensure_in_files_loaded()

        file_paths, message = input_file_names_to_file_path(' '.join(sorted(self.in_files)), self.in_files)
        count = legitimate_count = 0
        scores = []

        for file in file_paths:
            print(f"\nReading file {os.path.basename(file)}...")
            G, H, alpha = input_file_to_instance(file)
            print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
            print('Graph constructed...')
            start_time = time.time()
            ptp_tour, ptp_pick_up_locs_dict = ptp_solver(G, H, alpha)
            ptp_time = time.time() - start_time
            print('Tour generated by PTP solver...')
            print("Writing solution to output file...")
            write_ptp_solution_to_out(ptp_tour, ptp_pick_up_locs_dict, os.path.basename(file))
            print("Output written.")
            print('Analyzing the solution...')
            ptp_is_legitimate, ptp_driving_cost, ptp_walking_cost = analyze_solution(G, H, alpha, ptp_tour, ptp_pick_up_locs_dict)
            ptp_cost = ptp_driving_cost + ptp_walking_cost
            if ptp_is_legitimate:
                legitimate_count += 1
            print(f"Your PTP solution is{' NOT' if not ptp_is_legitimate else ''} legitimate.")
            print(f"Total cost: {ptp_cost:.5f}")
            print(f"Driving cost: {ptp_driving_cost:.5f}")
            print(f"Walking cost: {ptp_walking_cost:.5f}")
            print(f"Running time: {ptp_time:.5f} seconds")
            scores.append(ptp_cost)
            count += 1

        print(f"\nSuccessfully tested {count} files \n {legitimate_count} legitimate")
        print(f"Average cost: {sum(scores)/len(scores):.5f}")
        if message:
            print(message)


####### ------------------ #######
# Old implementation below
####### ------------------ #######

# prompt_message = """
# ---------------------------------------------
# Enter a command or type 'exit' to quit
# Type '--help' to get more information
# ----------------------------------------------
# """

# help_message = """
# Commands:
#   exit: quit the client
#   ls_input: list all input files (default under ./inputs folder)
#   ck_input: check whether student created inputs are valid or not
#   test_php: test php solver 
#   test_ptp: test ptp solver
#   test_php_all: test php solver on all input files
#   test_ptp_all: test ptp solver on all input files
#   --help: get help instructions
# """

# in_files = []
# stu_in_files = ['20_03.in', '20_10.in', '40_03.in', '40_10.in']


# def main_cli():
#     """
#     The main client which continues reading input from user and execute corresponding instructions
#     """
#     global in_files, stu_in_files
#     print(f"{TITLE_ART}")
#     while True:
#         user_input = input(prompt_message)

#         # exit the client
#         if user_input.lower() == "exit":
#             print("Exit the client")
#             break

#         # get help
#         elif user_input.lower() == "--help":
#             print(help_message)

#         # list all input files
#         elif '_'.join(re.split('[_,.\s-]', user_input.lower())) == "ls_input":
#             print(f"Listing input files under {INPUT_FILE_DIRECTORY}")
#             if len(in_files) == 0:
#                 in_files = get_files_with_extension(os.path.join(os.getcwd(), INPUT_FILE_DIRECTORY), extension=".in")
#             for file in in_files:
#                 print(file)

#         # check whether student created inputs are valid or not
#         elif '_'.join(re.split('[_,.\s-]', user_input.lower())) == "ck_input":
#             print("Checking whether student created inputs are legitimate...")
#             print(f"Searching for specified inputs {stu_in_files}")
#             if len(in_files) == 0:
#                 in_files = get_files_with_extension(os.path.join(os.getcwd(), INPUT_FILE_DIRECTORY), extension=".in")
#             file_paths, in_message = input_file_names_to_file_path(' '.join(sorted(in_files)), in_files)
#             count = 0
#             valid_count = 0
#             for file in file_paths:
#                 file_basename = os.path.basename(file)
#                 if file_basename in stu_in_files:
#                     print(f"\nChecking file {file_basename}...")
#                     is_valid, message = is_valid_input(file)
#                     if is_valid:
#                         print("The input is valid")
#                         valid_count += 1
#                     else:
#                         print(f"The input is not valid. Error message:\n{message}")
#                     count += 1
#             print(f"\nSucessfully check {count} files \n {count - valid_count} invalid")
#             if in_message:
#                 print(in_message)

#         # test php solver on specified input files
#         elif '_'.join(re.split('[_,.\s-]', user_input.lower())) == "test_php":
#             print("Testing php solver...")
#             # prompt for specifying input files
#             user_in_files_str = input(f"Select input files: ")
#             print("Starting testing php solver...")
#             if len(in_files) == 0:
#                 in_files = get_files_with_extension(os.path.join(os.getcwd(), INPUT_FILE_DIRECTORY), extension=".in")
#             file_paths, message = input_file_names_to_file_path(user_in_files_str, in_files)
#             count = 0
#             legitimate_count = 0
#             for file in file_paths:
#                 print(f"\nReading file {os.path.basename(file)}...")
#                 G, H, alpha = input_file_to_instance(file)
#                 print('Graph constructed...')
#                 print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
#                 tour = php_solver_from_tsp(G, H)
#                 print('Tour generated by php solver...')
#                 print('Analyzing the solution...')
#                 is_legitimate, driving_cost, walking_cost = analyze_solution(G, H, alpha, tour, {})
#                 if is_legitimate: legitimate_count += 1
#                 print(f"Your solution is {'NOT' if not is_legitimate else ''} legimitate.")
#                 print(f"Total driving cost of your soluton: {driving_cost:.5f}")
#                 # print(f"Total walking cost of your soluton: {walking_cost:.5f}")
#                 count += 1
#             print(f"\nSucessfully test {count} files \n {count-legitimate_count} solutions NOT legitimate")
#             legitimate_count = 0
#             if message:
#                 print(message)
                
#         # test ptp solver on specified input files
#         elif '_'.join(re.split('[_,.\s-]', user_input.lower())) == "test_ptp":
#             print("Testing PTP solver...")
#             # prompt for specifying input files
#             user_in_files_str = input(f"Select input files: ")
#             print("Strating testing PTP solver...")
#             if len(in_files) == 0:
#                 in_files = get_files_with_extension(os.path.join(os.getcwd(), INPUT_FILE_DIRECTORY), extension=".in")
#             file_paths, message = input_file_names_to_file_path(user_in_files_str, in_files)
#             count = 0
#             legitimate_count = 0
#             for file in file_paths:
#                 print(f"\nReading file {os.path.basename(file)}...")
#                 G, H, alpha = input_file_to_instance(file)
#                 print('Graph constructed...')
#                 print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
#                 tour, pick_up_locs_dict = ptp_solver(G, H, alpha)
#                 print('Tour generated by PTP solver...')
#                 print("Writing solution to output file...")
#                 write_ptp_solution_to_out(tour, pick_up_locs_dict, os.path.basename(file))
#                 print("Output written.")
#                 print('Analyzing the solution...')
#                 is_legitimate, driving_cost, walking_cost = analyze_solution(G, H, alpha, tour, pick_up_locs_dict)
#                 if is_legitimate: legitimate_count += 1
#                 print(f"Your solution is{' NOT' if not is_legitimate else ''} legimitate.")
#                 print(f"Total driving cost of your soluton: {driving_cost:.5f}")
#                 print(f"Total walking cost of your soluton: {walking_cost:.5f}")
#                 count += 1
#             print(f"\nSucessfully test {count} files \n {count-legitimate_count} solutions NOT legitimate")
#             legitimate_count = 0
#             if message:
#                 print(message)   
                
#         # test php solver over all input files
#         elif '_'.join(re.split('[_,.\s-]', user_input.lower())) == "test_php_all":
#             # prompt for specifying input files
#             print("Testing php solver on all inputs...")
#             if len(in_files) == 0:
#                 in_files = get_files_with_extension(os.path.join(os.getcwd(), INPUT_FILE_DIRECTORY), extension=".in")
#             file_paths, message = input_file_names_to_file_path(' '.join(sorted(in_files)), in_files)
#             count = 0
#             legitimate_count = 0
#             scores = []
#             for file in file_paths:
#                 print(f"\nReading file {os.path.basename(file)}...")
#                 G, H, alpha = input_file_to_instance(file)
#                 print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
#                 print('Graph constructed...')
#                 start_time = time.time()
#                 php_tour = php_solver_from_tsp(G, H)
#                 php_time = time.time() - start_time
#                 print('Tour generated by php solver...')
#                 # start_time = time.time()
#                 # ptp_tour, ptp_pick_up_locs_dict = ptp_solver(G, H, alpha)
#                 # ptp_time = time.time() - start_time
#                 # print('Tour generated by PTP solver...')
#                 # print("Writing solution to output file...")
#                 # write_ptp_solution_to_out(ptp_tour, ptp_pick_up_locs_dict, os.path.basename(file))
#                 # print("Output written.")
#                 print('Analyzing the solution...')
#                 php_is_legitimate, php_driving_cost, php_walking_cost = analyze_solution(G, H, alpha, php_tour, {})
#                 php_cost = php_driving_cost + php_walking_cost
#                 if php_is_legitimate: legitimate_count += 1
#                 # ptp_is_legitimate, ptp_driving_cost, ptp_walking_cost = analyze_solution(G, H, alpha, ptp_tour, ptp_pick_up_locs_dict)
#                 # ptp_cost = ptp_driving_cost + ptp_walking_cost
#                 print(f"Your php solution is{' NOT' if not php_is_legitimate else ''} legimitate.")
#                 print(f"Total cost of your php soluton: {php_cost:.5f}")
#                 # print(f"Total driving cost of your php solution: {php_driving_cost:.5f}")
#                 # print(f"Total walking cost of your php solution: {php_walking_cost:.5f}")
#                 print(f"Running time of your php solver: {php_time:.5f} seconds")
#                 # print(f"Your PTP solution is{' NOT' if not ptp_is_legitimate else ''} legimitate.")
#                 # print(f"Total cost of your PTP solution: {ptp_cost:.5f}")
#                 # print(f"Total driving cost of your PTP solution: {ptp_driving_cost:.5f}")
#                 # print(f"Total walking cost of your PTP solution: {ptp_walking_cost:.5f}")
#                 # print(f"Running time of your PTP solver: {ptp_time:.5f} seconds")
#                 scores.append(php_cost)
#                 count += 1
#             print(f"\nSucessfully test {count} files \n {count-legitimate_count} solutions NOT legitimate")
#             print(f"Average cost of your php solver: {sum(scores)/len(scores):.5f}")
#             legitimate_count = 0 
#             if message:
#                 print(message)      

#         # test ptp solver on all input files
#         elif '_'.join(re.split('[_,.\s-]', user_input.lower())) == "test_ptp_all":
#             # prompt for specifying input files
#             print("Testing PTP solver on all inputs...")
#             if len(in_files) == 0:
#                 in_files = get_files_with_extension(os.path.join(os.getcwd(), INPUT_FILE_DIRECTORY), extension=".in")
#             file_paths, message = input_file_names_to_file_path(' '.join(sorted(in_files)), in_files)
#             count = 0
#             legitimate_count = 0
#             scores = []
#             for file in file_paths:
#                 print(f"\nReading file {os.path.basename(file)}...")
#                 G, H, alpha = input_file_to_instance(file)
#                 print(f"n = {G.number_of_nodes()}, |H| = {len(H)}, alpha = {alpha}")
#                 print('Graph constructed...')
#                 # start_time = time.time()
#                 # php_tour = php_solver_from_tsp(G, H)
#                 # php_time = time.time() - start_time
#                 # print('Tour generated by php solver...')
#                 start_time = time.time()
#                 ptp_tour, ptp_pick_up_locs_dict = ptp_solver(G, H, alpha)
#                 ptp_time = time.time() - start_time
#                 print('Tour generated by PTP solver...')
#                 print("Writing solution to output file...")
#                 write_ptp_solution_to_out(ptp_tour, ptp_pick_up_locs_dict, os.path.basename(file))
#                 print("Output written.")
#                 print('Analyzing the solution...')
#                 # php_is_legitimate, php_driving_cost, php_walking_cost = analyze_solution(G, H, alpha, php_tour, {})
#                 # php_cost = php_driving_cost + php_walking_cost
#                 ptp_is_legitimate, ptp_driving_cost, ptp_walking_cost = analyze_solution(G, H, alpha, ptp_tour, ptp_pick_up_locs_dict)
#                 ptp_cost = ptp_driving_cost + ptp_walking_cost
#                 # print(f"Your php solution is{' NOT' if not php_is_legitimate else ''} legimitate.")
#                 # print(f"Total cost of your php soluton: {php_cost:.5f}")
#                 # print(f"Running time of your php solver: {php_time:.5f} seconds")
#                 if ptp_is_legitimate: legitimate_count += 1
#                 print(f"Your PTP solution is{' NOT' if not ptp_is_legitimate else ''} legimitate.")
#                 print(f"Total cost of your PTP solution: {ptp_cost:.5f}")
#                 print(f"Total driving cost of your PTP solution: {ptp_driving_cost:.5f}")
#                 print(f"Total walking cost of your PTP solution: {ptp_walking_cost:.5f}")
#                 print(f"Running time of your PTP solver: {ptp_time:.5f} seconds")
#                 scores.append(ptp_cost)
#                 count += 1
#             print(f"\nSucessfully test {count} files \n {count-legitimate_count} solutions NOT legitimate ")
#             print(f"Average cost of your PTP solver: {sum(scores)/len(scores):.5f}")
#             legitimate_count = 0
#             if message:
#                 print(message)

#         else:
#             print("Command not found.\nType '--help' to get instruction list")
     